In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
acc_df = pd.read_csv("accepted_2007_to_2018Q4.csv.gz", compression='gzip', low_memory=False)

# 기본 EDA

In [7]:
acc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Columns: 151 entries, id to settlement_term
dtypes: float64(113), object(38)
memory usage: 2.5+ GB

In [8]:
# 최대 1000개의 행까지 출력
pd.options.display.max_rows = 1000

In [9]:
# 행 출력 최대 개수
pd.options.display.max_rows

1000

In [10]:
acc_df.head().T

,0,1,2,3,4
id,68407277,68355089,68341763,66310712,68476807
member_id,NaN,NaN,NaN,NaN,NaN
loan_amnt,3600.0,24700.0,20000.0,35000.0,10400.0
funded_amnt,3600.0,24700.0,20000.0,35000.0,10400.0
funded_amnt_inv,3600.0,24700.0,20000.0,35000.0,10400.0
term,36 months,36 months,60 months,60 months,60 months
int_rate,13.99,11.99,10.78,14.85,22.45
installment,123.03,820.28,432.66,829.9,289.91
grade,C,C,B,C,F
sub_grade,C4,C1,B4,C5,F1
emp_title,leadman,Engineer,truck driver,Information Systems Officer,Contract Specialist
emp_length,10+ years,10+ years,10+ years,10+ years,3 years
home_ownership,MORTGAGE,MORTGAGE,MORTGAGE,MORTGAGE,MORTGAGE
annual_inc,55000.0,65000.0,63000.0,110000.0,104433.0
verification_status,Not Verified,Not Verified,Not Verified,Source Verified,Source Verified
issue_d,Dec-2015,Dec-2015,Dec-2015,Dec-2015,Dec-2015
loan_status,Fully Paid,Fully Paid,Fully Paid,Current,Fully Paid
pymnt_plan,n,n,n,n,n
url,https://lendingclub.com/browse/loanDetail.acti...,https://lendingclub.com/browse/loanDetail.acti...,https://lendingclub.com/browse/loanDetail.acti...,https://lendingclub.com/browse/loanDetail.acti...,https://lendingclub.com/browse/loanDetail.acti...
desc,NaN,NaN,NaN,NaN,NaN
purpose,debt_consolidation,small_business,home_improvement,debt_consolidation,major_purchase
title,Debt consolidation,Business,NaN,Debt consolidation,Major purchase
zip_code,190xx,577xx,605xx,076xx,174xx
addr_state,PA,SD,IL,NJ,PA
dti,5.91,16.06,10.78,17.06,25.37
delinq_2yrs,0.0,1.0,0.0,0.0,1.0
earliest_cr_line,Aug-2003,Dec-1999,Aug-2000,Sep-2008,Jun-1998
fico_range_low,675.0,715.0,695.0,785.0,695.0
fico_range_high,679.0,719.0,699.0,789.0,699.0
inq_last_6mths,1.0,4.0,0.0,0.0,3.0
mths_since_last_delinq,30.0,6.0,NaN,NaN,12.0
mths_since_last_record,NaN,NaN,NaN,NaN,NaN
open_acc,7.0,22.0,6.0,13.0,12.0
pub_rec,0.0,0.0,0.0,0.0,0.0
revol_bal,2765.0,21470.0,7869.0,7802.0,21929.0
revol_util,29.7,19.2,56.2,11.6,64.5
total_acc,13.0,38.0,18.0,17.0,35.0
initial_list_status,w,w,w,w,w
out_prncp,0.0,0.0,0.0,15897.65,0.0
out_prncp_inv,0.0,0.0,0.0,15897.65,0.0
total_pymnt,4421.723917,25679.66,22705.924294,31464.01,11740.5
total_pymnt_inv,4421.72,25679.66,22705.92,31464.01,11740.5
total_rec_prncp,3600.0,24700.0,20000.0,19102.35,10400.0
total_rec_int,821.72,979.66,2705.92,12361.66,1340.5
total_rec_late_fee,0.0,0.0,0.0,0.0,0.0
recoveries,0.0,0.0,0.0,0.0,0.0
collection_recovery_fee,0.0,0.0,0.0,0.0,0.0
last_pymnt_d,Jan-2019,Jun-2016,Jun-2017,Feb-2019,Jul-2016
last_pymnt_amnt,122.67,926.35,15813.3,829.9,10128.96
next_pymnt_d,NaN,NaN,NaN,Apr-2019,NaN
last_credit_pull_d,Mar-2019,Mar-2019,Mar-2019,Mar-2019,Mar-2018
last_fico_range_high,564.0,699.0,704.0,679.0,704.0
last_fico_range_low,560.0,695.0,700.0,675.0,700.0
collections_12_mths_ex_med,0.0,0.0,0.0,0.0,0.0
mths_since_last_major_derog,30.0,NaN,NaN,NaN,NaN
policy_code,1.0,1.0,1.0,1.0,1.0
application_type,Individual,Individual,Joint App,Individual,Individual
annual_inc_joint,NaN,NaN,71000.0,NaN,NaN
dti_joint,NaN,NaN,13.85,NaN,NaN
verification_status_joint,NaN,NaN,Not Verified,NaN,NaN
acc_now_delinq,0.0,0.0,0.0,0.0,0.0
tot_coll_amt,722.0,0.0,0.0,0.0,0.0
tot_cur_bal,144904.0,204396.0,189699.0,301500.0,331730.0
open_acc_6m,2.0,1.0,0.0,1.0,1.0
open_act_il,2.0,1.0,1.0,1.0,3.0
open_il_12m,0.0,0.0,0.0,0.0,0.0
open_il_24m,1.0,1.0,4.0,1.0,3.0
mths_since_rcnt_il,21.0,19.0,19.0,23.0,14.0
total_bal_il,4981.0,18005.0,10827.0,12609.0,73839.0
il_util,36.0,73.0,73.0,70.0,84.0
open_rv_12m,3.0,2.0,0.0,1.0,4.0
open_rv_24m,3.0,3.0,2.0,1.0,7.0
max_bal_bc,722.0,6472.0,2081.0,6987.0,9702.0
all_util,34.0,29.0,65.0,45.0,78.0
total_rev_hi_lim,9300.0,111800.0,14000.0,67300.0,34000.0
inq_fi,3.0,0.0,2.0,0.0,2.0
total_cu_tl,1.0,0.0,5.0,1.0,1.0
inq_last_12m,4.0,6.0,1.0,0.0,3.0
acc_open_past_24mths,4.0,4.0,6.0,2.0,10.0
avg_cur_bal,20701.0,9733.0,31617.0,23192.0,27644.0
bc_open_to_buy,1506.0,57830.0,2737.0,54962.0,4567.0
bc_util,37.2,27.1,55.9,12.1,77.5
chargeoff_within_12_mths,0.0,0.0,0.0,0.0,0.0
delinq_amnt,0.0,0.0,0.0,0.0,0.0
mo_sin_old_il_acct,148.0,113.0,125.0,36.0,128.0
mo_sin_old_rev_tl_op,128.0,192.0,184.0,87.0,210.0
mo_sin_rcnt_rev_tl_op,3.0,2.0,14.0,2.0,4.0
mo_sin_rcnt_tl,3.0,2.0,14.0,2.0,4.0
mort_acc,1.0,4.0,5.0,1.0,6.0
mths_since_recent_bc,4.0,2.0,101.0,2.0,4.0
mths_since_recent_bc_dlq,69.0,NaN,NaN,NaN,12.0
mths_since_recent_inq,4.0,0.0,10.0,NaN,1.0
mths_since_recent_revol_delinq,69.0,6.0,NaN,NaN,12.0
num_accts_ever_120_pd,2.0,0.0,0.0,0.0,0.0
num_actv_bc_tl,2.0,5.0,2.0,4.0,4.0
num_actv_rev_tl,4.0,5.0,3.0,5.0,6.0
num_bc_sats,2.0,13.0,2.0,8.0,5.0
num_bc_tl,5.0,17.0,4.0,10.0,9.0
num_il_tl,3.0,6.0,6.0,2.0,10.0
num_op_rev_tl,4.0,20.0,4.0,10.0,7.0
num_rev_accts,9.0,27.0,7.0,13.0,19.0
num_rev_tl_bal_gt_0,4.0,5.0,3.0,5.0,6.0
num_sats,7.0,22.0,6.0,13.0,12.0
num_tl_120dpd_2m,0.0,0.0,0.0,0.0,0.0
num_tl_30dpd,0.0,0.0,0.0,0.0,0.0
num_tl_90g_dpd_24m,0.0,0.0,0.0,0.0,0.0
num_tl_op_past_12m,3.0,2.0,0.0,1.0,4.0
pct_tl_nvr_dlq,76.9,97.4,100.0,100.0,96.6
percent_bc_gt_75,0.0,7.7,50.0,0.0,60.0
pub_rec_bankruptcies,0.0,0.0,0.0,0.0,0.0
tax_liens,0.0,0.0,0.0,0.0,0.0
tot_hi_cred_lim,178050.0,314017.0,218418.0,381215.0,439570.0
total_bal_ex_mort,7746.0,39475.0,18696.0,52226.0,95768.0
total_bc_limit,2400.0,79300.0,6200.0,62500.0,20300.0
total_il_high_credit_limit,13734.0,24667.0,14877.0,18000.0,88097.0
revol_bal_joint,NaN,NaN,NaN,NaN,NaN
sec_app_fico_range_low,NaN,NaN,NaN,NaN,NaN
sec_app_fico_range_high,NaN,NaN,NaN,NaN,NaN
sec_app_earliest_cr_line,NaN,NaN,NaN,NaN,NaN
sec_app_inq_last_6mths,NaN,NaN,NaN,NaN,NaN
sec_app_mort_acc,NaN,NaN,NaN,NaN,NaN
sec_app_open_acc,NaN,NaN,NaN,NaN,NaN
sec_app_revol_util,NaN,NaN,NaN,NaN,NaN
sec_app_open_act_il,NaN,NaN,NaN,NaN,NaN
sec_app_num_rev_accts,NaN,NaN,NaN,NaN,NaN
sec_app_chargeoff_within_12_mths,NaN,NaN,NaN,NaN,NaN
sec_app_collections_12_mths_ex_med,NaN,NaN,NaN,NaN,NaN
sec_app_mths_since_last_major_derog,NaN,NaN,NaN,NaN,NaN
hardship_flag,N,N,N,N,N
hardship_type,NaN,NaN,NaN,NaN,NaN
hardship_reason,NaN,NaN,NaN,NaN,NaN
hardship_status,NaN,NaN,NaN,NaN,NaN
deferral_term,NaN,NaN,NaN,NaN,NaN
hardship_amount,NaN,NaN,NaN,NaN,NaN
hardship_start_date,NaN,NaN,NaN,NaN,NaN
hardship_end_date,NaN,NaN,NaN,NaN,NaN
payment_plan_start_date,NaN,NaN,NaN,NaN,NaN
hardship_length,NaN,NaN,NaN,NaN,NaN
hardship_dpd,NaN,NaN,NaN,NaN,NaN
hardship_loan_status,NaN,NaN,NaN,NaN,NaN
orig_projected_additional_accrued_interest,NaN,NaN,NaN,NaN,NaN
hardship_payoff_balance_amount,NaN,NaN,NaN,NaN,NaN
hardship_last_payment_amount,NaN,NaN,NaN,NaN,NaN
disbursement_method,Cash,Cash,Cash,Cash,Cash
debt_settlement_flag,N,N,N,N,N
debt_settlement_flag_date,NaN,NaN,NaN,NaN,NaN
settlement_status,NaN,NaN,NaN,NaN,NaN
settlement_date,NaN,NaN,NaN,NaN,NaN
settlement_amount,NaN,NaN,NaN,NaN,NaN
settlement_percentage,NaN,NaN,NaN,NaN,NaN
settlement_term,NaN,NaN,NaN,NaN,NaN

In [11]:
acc_df.tail().T

,2260696,2260697,2260698,2260699,2260700
id,88985880,88224441,88215728,Total amount funded in policy code 1: 1465324575,Total amount funded in policy code 2: 521953170
member_id,NaN,NaN,NaN,NaN,NaN
loan_amnt,40000.0,24000.0,14000.0,NaN,NaN
funded_amnt,40000.0,24000.0,14000.0,NaN,NaN
funded_amnt_inv,40000.0,24000.0,14000.0,NaN,NaN
term,60 months,60 months,60 months,NaN,NaN
int_rate,10.49,14.49,14.49,NaN,NaN
installment,859.56,564.56,329.33,NaN,NaN
grade,B,C,C,NaN,NaN
sub_grade,B3,C4,C4,NaN,NaN
emp_title,Vice President,Program Manager,Customer Service Technician,NaN,NaN
emp_length,9 years,6 years,10+ years,NaN,NaN
home_ownership,MORTGAGE,RENT,MORTGAGE,NaN,NaN
annual_inc,227000.0,110000.0,95000.0,NaN,NaN
verification_status,Verified,Not Verified,Verified,NaN,NaN
issue_d,Oct-2016,Oct-2016,Oct-2016,NaN,NaN
loan_status,Current,Charged Off,Current,NaN,NaN
pymnt_plan,n,n,n,NaN,NaN
url,https://lendingclub.com/browse/loanDetail.acti...,https://lendingclub.com/browse/loanDetail.acti...,https://lendingclub.com/browse/loanDetail.acti...,NaN,NaN
desc,NaN,NaN,NaN,NaN,NaN
purpose,debt_consolidation,debt_consolidation,debt_consolidation,NaN,NaN
title,NaN,Debt consolidation,NaN,NaN,NaN
zip_code,907xx,334xx,770xx,NaN,NaN
addr_state,CA,FL,TX,NaN,NaN
dti,12.75,18.3,23.36,NaN,NaN
delinq_2yrs,7.0,0.0,0.0,NaN,NaN
earliest_cr_line,Feb-1995,Jul-1999,Jun-1996,NaN,NaN
fico_range_low,705.0,660.0,660.0,NaN,NaN
fico_range_high,709.0,664.0,664.0,NaN,NaN
inq_last_6mths,1.0,0.0,1.0,NaN,NaN
mths_since_last_delinq,9.0,67.0,37.0,NaN,NaN
mths_since_last_record,NaN,72.0,NaN,NaN,NaN
open_acc,5.0,10.0,8.0,NaN,NaN
pub_rec,0.0,1.0,0.0,NaN,NaN
revol_bal,8633.0,17641.0,7662.0,NaN,NaN
revol_util,64.9,68.1,54.0,NaN,NaN
total_acc,37.0,31.0,22.0,NaN,NaN
initial_list_status,f,f,w,NaN,NaN
out_prncp,23252.59,0.0,8456.12,NaN,NaN
out_prncp_inv,23252.59,0.0,8456.12,NaN,NaN
total_pymnt,24903.93,6755.4,9621.25,NaN,NaN
total_pymnt_inv,24903.93,6755.4,9621.25,NaN,NaN
total_rec_prncp,16747.41,3521.91,5543.88,NaN,NaN
total_rec_int,8156.52,3233.49,4027.96,NaN,NaN
total_rec_late_fee,0.0,0.0,49.41,NaN,NaN
recoveries,0.0,0.0,0.0,NaN,NaN
collection_recovery_fee,0.0,0.0,0.0,NaN,NaN
last_pymnt_d,Mar-2019,Oct-2017,Mar-2019,NaN,NaN
last_pymnt_amnt,859.56,564.56,329.33,NaN,NaN
next_pymnt_d,Apr-2019,NaN,Apr-2019,NaN,NaN
last_credit_pull_d,Mar-2019,Mar-2019,Mar-2019,NaN,NaN
last_fico_range_high,724.0,594.0,669.0,NaN,NaN
last_fico_range_low,720.0,590.0,665.0,NaN,NaN
collections_12_mths_ex_med,0.0,0.0,0.0,NaN,NaN
mths_since_last_major_derog,10.0,67.0,37.0,NaN,NaN
policy_code,1.0,1.0,1.0,NaN,NaN
application_type,Individual,Individual,Individual,NaN,NaN
annual_inc_joint,NaN,NaN,NaN,NaN,NaN
dti_joint,NaN,NaN,NaN,NaN,NaN
verification_status_joint,NaN,NaN,NaN,NaN,NaN
acc_now_delinq,0.0,0.0,0.0,NaN,NaN
tot_coll_amt,0.0,0.0,0.0,NaN,NaN
tot_cur_bal,28398.0,62426.0,143066.0,NaN,NaN
open_acc_6m,0.0,0.0,0.0,NaN,NaN
open_act_il,2.0,2.0,1.0,NaN,NaN
open_il_12m,0.0,0.0,1.0,NaN,NaN
open_il_24m,1.0,2.0,2.0,NaN,NaN
mths_since_rcnt_il,15.0,20.0,7.0,NaN,NaN
total_bal_il,19765.0,44785.0,32071.0,NaN,NaN
il_util,46.0,78.0,94.0,NaN,NaN
open_rv_12m,0.0,1.0,0.0,NaN,NaN
open_rv_24m,0.0,5.0,1.0,NaN,NaN
max_bal_bc,5141.0,6172.0,4093.0,NaN,NaN
all_util,51.0,73.0,84.0,NaN,NaN
total_rev_hi_lim,13300.0,25900.0,14200.0,NaN,NaN
inq_fi,3.0,0.0,3.0,NaN,NaN
total_cu_tl,0.0,0.0,1.0,NaN,NaN
inq_last_12m,2.0,1.0,2.0,NaN,NaN
acc_open_past_24mths,2.0,7.0,3.0,NaN,NaN
avg_cur_bal,5680.0,6243.0,17883.0,NaN,NaN
bc_open_to_buy,4070.0,4660.0,1838.0,NaN,NaN
bc_util,66.9,77.5,80.7,NaN,NaN
chargeoff_within_12_mths,0.0,0.0,0.0,NaN,NaN
delinq_amnt,0.0,0.0,0.0,NaN,NaN
mo_sin_old_il_acct,154.0,132.0,149.0,NaN,NaN
mo_sin_old_rev_tl_op,258.0,206.0,243.0,NaN,NaN
mo_sin_rcnt_rev_tl_op,33.0,9.0,22.0,NaN,NaN
mo_sin_rcnt_tl,15.0,9.0,7.0,NaN,NaN
mort_acc,3.0,2.0,1.0,NaN,NaN
mths_since_recent_bc,41.0,9.0,75.0,NaN,NaN
mths_since_recent_bc_dlq,9.0,NaN,39.0,NaN,NaN
mths_since_recent_inq,1.0,9.0,6.0,NaN,NaN
mths_since_recent_revol_delinq,9.0,NaN,37.0,NaN,NaN
num_accts_ever_120_pd,6.0,1.0,4.0,NaN,NaN
num_actv_bc_tl,2.0,5.0,3.0,NaN,NaN
num_actv_rev_tl,3.0,7.0,3.0,NaN,NaN
num_bc_sats,2.0,5.0,4.0,NaN,NaN
num_bc_tl,15.0,15.0,12.0,NaN,NaN
num_il_tl,9.0,4.0,3.0,NaN,NaN
num_op_rev_tl,3.0,8.0,5.0,NaN,NaN
num_rev_accts,23.0,24.0,17.0,NaN,NaN
num_rev_tl_bal_gt_0,3.0,7.0,3.0,NaN,NaN
num_sats,5.0,10.0,8.0,NaN,NaN
num_tl_120dpd_2m,0.0,0.0,0.0,NaN,NaN
num_tl_30dpd,0.0,0.0,0.0,NaN,NaN
num_tl_90g_dpd_24m,7.0,0.0,0.0,NaN,NaN
num_tl_op_past_12m,0.0,1.0,1.0,NaN,NaN
pct_tl_nvr_dlq,75.7,96.2,81.8,NaN,NaN
percent_bc_gt_75,50.0,40.0,50.0,NaN,NaN
pub_rec_bankruptcies,0.0,1.0,0.0,NaN,NaN
tax_liens,0.0,0.0,0.0,NaN,NaN
tot_hi_cred_lim,55970.0,84664.0,163804.0,NaN,NaN
total_bal_ex_mort,28398.0,62426.0,44215.0,NaN,NaN
total_bc_limit,12300.0,20700.0,9500.0,NaN,NaN
total_il_high_credit_limit,42670.0,58764.0,34169.0,NaN,NaN
revol_bal_joint,NaN,NaN,NaN,NaN,NaN
sec_app_fico_range_low,NaN,NaN,NaN,NaN,NaN
sec_app_fico_range_high,NaN,NaN,NaN,NaN,NaN
sec_app_earliest_cr_line,NaN,NaN,NaN,NaN,NaN
sec_app_inq_last_6mths,NaN,NaN,NaN,NaN,NaN
sec_app_mort_acc,NaN,NaN,NaN,NaN,NaN
sec_app_open_acc,NaN,NaN,NaN,NaN,NaN
sec_app_revol_util,NaN,NaN,NaN,NaN,NaN
sec_app_open_act_il,NaN,NaN,NaN,NaN,NaN
sec_app_num_rev_accts,NaN,NaN,NaN,NaN,NaN
sec_app_chargeoff_within_12_mths,NaN,NaN,NaN,NaN,NaN
sec_app_collections_12_mths_ex_med,NaN,NaN,NaN,NaN,NaN
sec_app_mths_since_last_major_derog,NaN,NaN,NaN,NaN,NaN
hardship_flag,N,N,N,NaN,NaN
hardship_type,NaN,NaN,NaN,NaN,NaN
hardship_reason,NaN,NaN,NaN,NaN,NaN
hardship_status,NaN,NaN,NaN,NaN,NaN
deferral_term,NaN,NaN,NaN,NaN,NaN
hardship_amount,NaN,NaN,NaN,NaN,NaN
hardship_start_date,NaN,NaN,NaN,NaN,NaN
hardship_end_date,NaN,NaN,NaN,NaN,NaN
payment_plan_start_date,NaN,NaN,NaN,NaN,NaN
hardship_length,NaN,NaN,NaN,NaN,NaN
hardship_dpd,NaN,NaN,NaN,NaN,NaN
hardship_loan_status,NaN,NaN,NaN,NaN,NaN
orig_projected_additional_accrued_interest,NaN,NaN,NaN,NaN,NaN
hardship_payoff_balance_amount,NaN,NaN,NaN,NaN,NaN
hardship_last_payment_amount,NaN,NaN,NaN,NaN,NaN
disbursement_method,Cash,Cash,Cash,NaN,NaN
debt_settlement_flag,N,Y,N,NaN,NaN
debt_settlement_flag_date,NaN,Mar-2019,NaN,NaN,NaN
settlement_status,NaN,ACTIVE,NaN,NaN,NaN
settlement_date,NaN,Mar-2019,NaN,NaN,NaN
settlement_amount,NaN,10000.0,NaN,NaN,NaN
settlement_percentage,NaN,44.82,NaN,NaN,NaN
settlement_term,NaN,1.0,NaN,NaN,NaN

In [12]:
# 수치형 컬럼 통계 요약
acc_df.describe()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,...,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,0.0,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260664e+06,2.258957e+06,2.260639e+06,2.260668e+06,...,10917.0,10917.000000,10917.0,10917.000000,8651.000000,10917.000000,10917.000000,34246.000000,34246.000000,34246.000000
mean,NaN,1.504693e+04,1.504166e+04,1.502344e+04,1.309283e+01,4.458068e+02,7.799243e+04,1.882420e+01,3.068792e-01,6.985882e+02,...,3.0,155.045981,3.0,13.743886,454.798089,11636.883942,193.994321,5010.664267,47.780365,13.191322
std,NaN,9.190245e+03,9.188413e+03,9.192332e+03,4.832138e+00,2.671735e+02,1.126962e+05,1.418333e+01,8.672303e-01,3.301038e+01,...,0.0,129.040594,0.0,9.671178,375.385500,7625.988281,198.629496,3693.122590,7.311822,8.159980
min,NaN,5.000000e+02,5.000000e+02,0.000000e+00,5.310000e+00,4.930000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,6.100000e+02,...,3.0,0.640000,3.0,0.000000,1.920000,55.730000,0.010000,44.210000,0.200000,0.000000
25%,NaN,8.000000e+03,8.000000e+03,8.000000e+03,9.490000e+00,2.516500e+02,4.600000e+04,1.189000e+01,0.000000e+00,6.750000e+02,...,3.0,59.440000,3.0,5.000000,175.230000,5627.000000,44.440000,2208.000000,45.000000,6.000000
50%,NaN,1.290000e+04,1.287500e+04,1.280000e+04,1.262000e+01,3.779900e+02,6.500000e+04,1.784000e+01,0.000000e+00,6.900000e+02,...,3.0,119.140000,3.0,15.000000,352.770000,10028.390000,133.160000,4146.110000,45.000000,14.000000
75%,NaN,2.000000e+04,2.000000e+04,2.000000e+04,1.599000e+01,5.933200e+02,9.300000e+04,2.449000e+01,0.000000e+00,7.150000e+02,...,3.0,213.260000,3.0,22.000000,620.175000,16151.890000,284.190000,6850.172500,50.000000,18.000000
max,NaN,4.000000e+04,4.000000e+04,4.000000e+04,3.099000e+01,1.719830e+03,1.100000e+08,9.990000e+02,5.800000e+01,8.450000e+02,...,3.0,943.940000,3.0,37.000000,2680.890000,40306.410000,1407.860000,33601.000000,521.350000,181.000000

In [13]:
# 범주형 컬럼 고유값 및 빈도
acc_df.value_counts()

OverflowError: int too big to convert

In [ ]:
acc_df.isnull().sum()

id                             0
member_id                2260701
loan_amnt                     33
funded_amnt                   33
funded_amnt_inv               33
                          ...
settlement_status        2226455
settlement_date          2226455
settlement_amount        2226455
settlement_percentage    2226455
settlement_term          2226455
Length: 151, dtype: int64

In [ ]:
# --- 2. 각 컬럼의 결측치 비율 계산 및 출력 ---
print("--- acc_df의 각 컬럼 결측치 비율 (%) ---")
# 이제 acc_df를 사용합니다.
missing_percentages = acc_df.isnull().sum() / len(acc_df) * 100

# 결측치가 있는 컬럼만 보고 싶다면 아래와 같이 필터링하고 정렬할 수 있습니다.
missing_percentages = missing_percentages[missing_percentages > 0].sort_values(ascending=False)

print(missing_percentages)

--- acc_df의 각 컬럼 결측치 비율 (%) ---
member_id                                     100.000000
orig_projected_additional_accrued_interest     99.617331
hardship_payoff_balance_amount                 99.517097
hardship_last_payment_amount                   99.517097
payment_plan_start_date                        99.517097
hardship_type                                  99.517097
hardship_status                                99.517097
hardship_start_date                            99.517097
deferral_term                                  99.517097
hardship_amount                                99.517097
hardship_dpd                                   99.517097
hardship_loan_status                           99.517097
hardship_length                                99.517097
hardship_end_date                              99.517097
hardship_reason                                99.517097
debt_settlement_flag_date                      98.485160
settlement_status                              98.485160
settlement_percentage                          98.485160
settlement_date                                98.485160
settlement_amount                              98.485160
settlement_term                                98.485160
sec_app_mths_since_last_major_derog            98.410139
sec_app_revol_util                             95.303050
revol_bal_joint                                95.221836
sec_app_num_rev_accts                          95.221792
sec_app_open_acc                               95.221792
sec_app_earliest_cr_line                       95.221792
sec_app_inq_last_6mths                         95.221792
sec_app_mort_acc                               95.221792
sec_app_open_act_il                            95.221792
sec_app_fico_range_low                         95.221792
sec_app_fico_range_high                        95.221792
sec_app_chargeoff_within_12_mths               95.221792
sec_app_collections_12_mths_ex_med             95.221792
verification_status_joint                      94.880791
dti_joint                                      94.660683
annual_inc_joint                               94.660506
desc                                           94.423632
mths_since_last_record                         84.113069
mths_since_recent_bc_dlq                       77.011511
mths_since_last_major_derog                    74.309960
mths_since_recent_revol_delinq                 67.250910
next_pymnt_d                                   59.509993
mths_since_last_delinq                         51.246715
il_util                                        47.281042
mths_since_rcnt_il                             40.251099
all_util                                       38.323555
inq_last_12m                                   38.313912
open_acc_6m                                    38.313912
total_cu_tl                                    38.313912
open_il_24m                                    38.313868
open_act_il                                    38.313868
open_il_12m                                    38.313868
open_rv_24m                                    38.313868
max_bal_bc                                     38.313868
inq_fi                                         38.313868
total_bal_il                                   38.313868
open_rv_12m                                    38.313868
mths_since_recent_inq                          13.069751
emp_title                                       7.387178
num_tl_120dpd_2m                                6.798334
emp_length                                      6.499754
mo_sin_old_il_acct                              6.153136
bc_util                                         3.366389
percent_bc_gt_75                                3.335779
bc_open_to_buy                                  3.316140
mths_since_recent_bc                            3.248771
pct_tl_nvr_dlq                                  3.116909
avg_cur_bal                                     3.113149
num_rev_accts                                   3.110097
mo_sin_rcnt_rev_tl_op                           3.110097
mo_sin_old_rev_tl_op                            3.110097
num_op_rev_tl                                   3.110053
num_tl_op_past_12m                              3.110053
tot_coll_amt                                    3.110053
num_actv_rev_tl                                 3.110053
total_rev_hi_lim                                3.110053
tot_cur_bal                                     3.110053
num_tl_30dpd                                    3.110053
num_actv_bc_tl                                  3.110053
num_accts_ever_120_pd                           3.110053
num_rev_tl_bal_gt_0                             3.110053
mo_sin_rcnt_tl                                  3.110053
num_tl_90g_dpd_24m                              3.110053
tot_hi_cred_lim                                 3.110053
total_il_high_credit_limit                      3.110053
num_il_tl                                       3.110053
num_bc_tl                                       3.110053
num_bc_sats                                     2.593134
num_sats                                        2.593134
total_bal_ex_mort                               2.214490
total_bc_limit                                  2.214490
mort_acc                                        2.214490
acc_open_past_24mths                            2.214490
title                                           1.033264
last_pymnt_d                                    0.108816
revol_util                                      0.081170
dti                                             0.077144
pub_rec_bankruptcies                            0.061839
chargeoff_within_12_mths                        0.007874
collections_12_mths_ex_med                      0.007874
tax_liens                                       0.006104
last_credit_pull_d                              0.004645
inq_last_6mths                                  0.002787
total_acc                                       0.002743
open_acc                                        0.002743
earliest_cr_line                                0.002743
pub_rec                                         0.002743
delinq_2yrs                                     0.002743
acc_now_delinq                                  0.002743
delinq_amnt                                     0.002743
annual_inc                                      0.001637
zip_code                                        0.001504
term                                            0.001460
funded_amnt                                     0.001460
funded_amnt_inv                                 0.001460
int_rate                                        0.001460
loan_amnt                                       0.001460
purpose                                         0.001460
loan_status                                     0.001460
pymnt_plan                                      0.001460
url                                             0.001460
issue_d                                         0.001460
grade                                           0.001460
home_ownership                                  0.001460
verification_status                             0.001460
installment                                     0.001460
sub_grade                                       0.001460
revol_bal                                       0.001460
policy_code                                     0.001460
application_type                                0.001460
last_pymnt_amnt                                 0.001460
last_fico_range_low                             0.001460
addr_state                                      0.001460
out_prncp                                       0.001460
initial_list_status                             0.001460
last_fico_range_high                            0.001460
fico_range_low                                  0.001460
fico_range_high                                 0.001460
out_prncp_inv                                   0.001460
total_pymnt_inv                                 0.001460
total_pymnt                                     0.001460
collection_recovery_fee                         0.001460
recoveries                                      0.001460
total_rec_late_fee                              0.001460
total_rec_int                                   0.001460
total_rec_prncp                                 0.001460
hardship_flag                                   0.001460
disbursement_method                             0.001460
debt_settlement_flag                            0.001460
dtype: float64

In [ ]:
# --- 3. 결과를 텍스트 파일로 저장 ---
output_filename = 'acc_df_missing_percentages.txt'

try:
    with open(output_filename, 'w', encoding='utf-8') as f:
        f.write("--- acc_df 각 컬럼의 결측치 비율 (%) ---\n")
        # to_string() 메서드는 Pandas Series/DataFrame을 문자열로 변환합니다.
        # 이 변환은 일반적으로 display 옵션을 존중합니다.
        f.write(missing_percentages.to_string())
        f.write("\n")

    print(f"\n모든 컬럼의 결측치 비율이 '{output_filename}' 파일에 저장되었습니다.")
    print(f"파일이 저장된 위치: {os.getcwd()}") # 현재 작업 디렉토리 출력

except Exception as e:
    print(f"결측치 비율을 파일로 저장하는 중 오류가 발생했습니다: {e}")

모든 컬럼의 결측치 비율이 'acc_df_missing_percentages.txt' 파일에 저장되었습니다.
결측치 비율을 파일로 저장하는 중 오류가 발생했습니다: name 'os' is not defined

In [ ]:
df.columns.tolist()

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'fico_range_low',
 'fico_range_high',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'last_fico_range_high',
 'last_fico_range_low',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_fico_range_low',
 'sec_app_fico_range_high',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'disbursement_method',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [ ]:
# 모든 컬럼명 조회
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

print("\n--- 모든 컬럼 이름 ---")
column_names = df.columns.tolist()
#줄바꿈 해서 출력
for col_name in column_names:
    print(col_name)

--- 모든 컬럼 이름 ---
id
member_id
loan_amnt
funded_amnt
funded_amnt_inv
term
int_rate
installment
grade
sub_grade
emp_title
emp_length
home_ownership
annual_inc
verification_status
issue_d
loan_status
pymnt_plan
url
desc
purpose
title
zip_code
addr_state
dti
delinq_2yrs
earliest_cr_line
fico_range_low
fico_range_high
inq_last_6mths
mths_since_last_delinq
mths_since_last_record
open_acc
pub_rec
revol_bal
revol_util
total_acc
initial_list_status
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_d
last_pymnt_amnt
next_pymnt_d
last_credit_pull_d
last_fico_range_high
last_fico_range_low
collections_12_mths_ex_med
mths_since_last_major_derog
policy_code
application_type
annual_inc_joint
dti_joint
verification_status_joint
acc_now_delinq
tot_coll_amt
tot_cur_bal
open_acc_6m
open_act_il
open_il_12m
open_il_24m
mths_since_rcnt_il
total_bal_il
il_util
open_rv_12m
open_rv_24m
max_bal_bc
all_util
total_rev_hi_lim
inq_fi
total_cu_tl
inq_last_12m
acc_open_past_24mths
avg_cur_bal
bc_open_to_buy
bc_util
chargeoff_within_12_mths
delinq_amnt
mo_sin_old_il_acct
mo_sin_old_rev_tl_op
mo_sin_rcnt_rev_tl_op
mo_sin_rcnt_tl
mort_acc
mths_since_recent_bc
mths_since_recent_bc_dlq
mths_since_recent_inq
mths_since_recent_revol_delinq
num_accts_ever_120_pd
num_actv_bc_tl
num_actv_rev_tl
num_bc_sats
num_bc_tl
num_il_tl
num_op_rev_tl
num_rev_accts
num_rev_tl_bal_gt_0
num_sats
num_tl_120dpd_2m
num_tl_30dpd
num_tl_90g_dpd_24m
num_tl_op_past_12m
pct_tl_nvr_dlq
percent_bc_gt_75
pub_rec_bankruptcies
tax_liens
tot_hi_cred_lim
total_bal_ex_mort
total_bc_limit
total_il_high_credit_limit
revol_bal_joint
sec_app_fico_range_low
sec_app_fico_range_high
sec_app_earliest_cr_line
sec_app_inq_last_6mths
sec_app_mort_acc
sec_app_open_acc
sec_app_revol_util
sec_app_open_act_il
sec_app_num_rev_accts
sec_app_chargeoff_within_12_mths
sec_app_collections_12_mths_ex_med
sec_app_mths_since_last_major_derog
hardship_flag
hardship_type
hardship_reason
hardship_status
deferral_term
hardship_amount
hardship_start_date
hardship_end_date
payment_plan_start_date
hardship_length
hardship_dpd
hardship_loan_status
orig_projected_additional_accrued_interest
hardship_payoff_balance_amount
hardship_last_payment_amount
disbursement_method
debt_settlement_flag
debt_settlement_flag_date
settlement_status
settlement_date
settlement_amount
settlement_percentage
settlement_term

In [ ]:
# --- 모든 컬럼 이름을 파일로 저장 ---
output_filename = 'all_column_names.txt'

try:
    column_names = df.columns.tolist()

    with open(output_filename, 'w', encoding='utf-8') as f:
        f.write("--- 모든 컬럼 이름 ---\n")
        for col_name in column_names:
            f.write(col_name + '\n') # 각 컬럼 이름 뒤에 줄바꿈 추가

    print(f"\n모든 컬럼 이름이 '{output_filename}' 파일에 저장되었습니다.")
    print(f"파일이 저장된 위치: {os.getcwd()}") # 현재 작업 디렉토리 출력

except NameError:
    print("오류: 'df' DataFrame이 정의되지 않았습니다. 데이터를 먼저 불러와 주세요.")
except Exception as e:
    print(f"컬럼 이름을 파일로 저장하는 중 오류가 발생했습니다: {e}")

모든 컬럼 이름이 'all_column_names.txt' 파일에 저장되었습니다.
오류: 'df' DataFrame이 정의되지 않았습니다. 데이터를 먼저 불러와 주세요.

# 복사본 생성 후 작업

In [3]:
acc_df_cleaned = acc_df.copy()
acc_df_cleaned.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
missing_percentages = acc_df.isnull().sum() / len(acc_df) * 100
cols_to_drop = missing_percentages[missing_percentages >= 80].index.tolist()

print(f"--- 제거할 컬럼 목록 (결측치 비율 80% 이상) ---")
print(f"총 {len(cols_to_drop)}개의 컬럼이 제거 대상입니다.")
for col in cols_to_drop:
    print(f"- {col}: {missing_percentages[col]:.2f}%")

acc_df_cleaned = acc_df.drop(columns=cols_to_drop)

--- 제거할 컬럼 목록 (결측치 비율 80% 이상) ---
총 39개의 컬럼이 제거 대상입니다.
- member_id: 100.00%
- desc: 94.42%
- mths_since_last_record: 84.11%
- annual_inc_joint: 94.66%
- dti_joint: 94.66%
- verification_status_joint: 94.88%
- revol_bal_joint: 95.22%
- sec_app_fico_range_low: 95.22%
- sec_app_fico_range_high: 95.22%
- sec_app_earliest_cr_line: 95.22%
- sec_app_inq_last_6mths: 95.22%
- sec_app_mort_acc: 95.22%
- sec_app_open_acc: 95.22%
- sec_app_revol_util: 95.30%
- sec_app_open_act_il: 95.22%
- sec_app_num_rev_accts: 95.22%
- sec_app_chargeoff_within_12_mths: 95.22%
- sec_app_collections_12_mths_ex_med: 95.22%
- sec_app_mths_since_last_major_derog: 98.41%
- hardship_type: 99.52%
- hardship_reason: 99.52%
- hardship_status: 99.52%
- deferral_term: 99.52%
- hardship_amount: 99.52%
- hardship_start_date: 99.52%
- hardship_end_date: 99.52%
- payment_plan_start_date: 99.52%
- hardship_length: 99.52%
- hardship_dpd: 99.52%
- hardship_loan_status: 99.52%
- orig_projected_additional_accrued_interest: 99.62%
- hardship_payoff_balance_amount: 99.52%
- hardship_last_payment_amount: 99.52%
- debt_settlement_flag_date: 98.49%
- settlement_status: 98.49%
- settlement_date: 98.49%
- settlement_amount: 98.49%
- settlement_percentage: 98.49%
- settlement_term: 98.49%

In [ ]:
print(f"\n--- 컬럼 제거 결과 ---")
print(f"원본 DataFrame 컬럼 수: {acc_df.shape[1]}개")
print(f"제거 후 DataFrame 컬럼 수: {acc_df_cleaned.shape[1]}개")
print(f"제거된 컬럼 수: {acc_df.shape[1] - acc_df_cleaned.shape[1]}개")

print("\n제거 후 DataFrame의 상위 5개 행:")
print(acc_df_cleaned.head())

--- 컬럼 제거 결과 ---
원본 DataFrame 컬럼 수: 151개
제거 후 DataFrame 컬럼 수: 112개
제거된 컬럼 수: 39개

제거 후 DataFrame의 상위 5개 행:
         id  loan_amnt  funded_amnt  funded_amnt_inv        term  int_rate  \
0  68407277     3600.0       3600.0           3600.0   36 months     13.99
1  68355089    24700.0      24700.0          24700.0   36 months     11.99
2  68341763    20000.0      20000.0          20000.0   60 months     10.78
3  66310712    35000.0      35000.0          35000.0   60 months     14.85
4  68476807    10400.0      10400.0          10400.0   60 months     22.45

   installment grade sub_grade                    emp_title  ...  \
0       123.03     C        C4                      leadman  ...
1       820.28     C        C1                     Engineer  ...
2       432.66     B        B4                 truck driver  ...
3       829.90     C        C5  Information Systems Officer  ...
4       289.91     F        F1          Contract Specialist  ...

  percent_bc_gt_75 pub_rec_bankruptcies  tax_liens tot_hi_cred_lim  \
0              0.0                  0.0        0.0        178050.0
1              7.7                  0.0        0.0        314017.0
2             50.0                  0.0        0.0        218418.0
3              0.0                  0.0        0.0        381215.0
4             60.0                  0.0        0.0        439570.0

  total_bal_ex_mort total_bc_limit total_il_high_credit_limit hardship_flag  \
0            7746.0         2400.0                    13734.0             N
1           39475.0        79300.0                    24667.0             N
2           18696.0         6200.0                    14877.0             N
3           52226.0        62500.0                    18000.0             N
4           95768.0        20300.0                    88097.0             N

  disbursement_method debt_settlement_flag
0                Cash                    N
1                Cash                    N
2                Cash                    N
3                Cash                    N
4                Cash                    N

[5 rows x 112 columns]

In [5]:
bad_status = ['Charged Off', 'Default']
good_status = ['Fully Paid']

In [6]:
acc_df_target = acc_df_cleaned[acc_df['loan_status'].isin(good_status + bad_status)].copy()
acc_df_target.head()

,id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag
0,68407277,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,...,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,N,Cash,N
1,68355089,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,...,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,N,Cash,N
2,68341763,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,...,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,N,Cash,N
4,68476807,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,...,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,N,Cash,N
5,68426831,11950.0,11950.0,11950.0,36 months,13.44,405.18,C,C3,Veterinary Tecnician,...,100.0,0.0,0.0,16900.0,12798.0,9400.0,4000.0,N,Cash,N

In [7]:
acc_df_target['loan_status_binary'] = acc_df_target['loan_status'].apply(
    lambda x: 1 if x in bad_status else 0
)

In [ ]:
print(f"타겟 변수 필터링 후 데이터 크기: {acc_df_target.shape}")
print(f"정상 상환 (0) 대출 수: {acc_df_target[acc_df_target['loan_status_binary'] == 0].shape[0]}건")
print(f"부도 (1) 대출 수: {acc_df_target[acc_df_target['loan_status_binary'] == 1].shape[0]}건")
print(f"비율: 부도 {acc_df_target['loan_status_binary'].mean()*100:.2f}%")

타겟 변수 필터링 후 데이터 크기: (1345350, 113)
정상 상환 (0) 대출 수: 1076751건
부도 (1) 대출 수: 268599건
비율: 부도 19.96%

# 범주형 컬럼 전처리

In [8]:
# 범주형 컬럼 리스트 
cat_feat = [
    'term',
    'grade',
    'emp_title',
    'emp_length',
    'home_ownership',
    'verification_status',
    'purpose'
]

In [9]:
# 범주형 컬럼 데이터 프레임 생성
df_cat = acc_df_cleaned[cat_feat].copy()
df_cat.head()

,term,grade,emp_title,emp_length,home_ownership,verification_status,purpose
0,36 months,C,leadman,10+ years,MORTGAGE,Not Verified,debt_consolidation
1,36 months,C,Engineer,10+ years,MORTGAGE,Not Verified,small_business
2,60 months,B,truck driver,10+ years,MORTGAGE,Not Verified,home_improvement
3,60 months,C,Information Systems Officer,10+ years,MORTGAGE,Source Verified,debt_consolidation
4,60 months,F,Contract Specialist,3 years,MORTGAGE,Source Verified,major_purchase

In [10]:
df_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 7 columns):
 #   Column               Dtype
---  ------               -----
 0   term                 object
 1   grade                object
 2   emp_title            object
 3   emp_length           object
 4   home_ownership       object
 5   verification_status  object
 6   purpose              object
dtypes: object(7)
memory usage: 120.7+ MB

In [11]:
# 오브젝트 타입을 카테고리 타입으로 변환하여 메모리, 처리 효율성 증대시키기
for col in df_cat.columns:
    df_cat[col] = df_cat[col].astype('category')

In [12]:
df_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 7 columns):
 #   Column               Dtype
---  ------               -----
 0   term                 category
 1   grade                category
 2   emp_title            category
 3   emp_length           category
 4   home_ownership       category
 5   verification_status  category
 6   purpose              category
dtypes: category(7)
memory usage: 41.6 MB

In [13]:
# 각 컬럼 결측치 개수
df_cat.isnull().sum()

term                       33
grade                      33
emp_title              167002
emp_length             146940
home_ownership             33
verification_status        33
purpose                    33
dtype: int64

In [ ]:
# 각 컬럼의 결측치 비율 계산 및 출력 
missing_per_cat = df_cat.isnull().sum() / len(acc_df) * 100

# 결측치가 있는 컬럼만 보고 싶다면 아래와 같이 필터링하고 정렬
#missing_per_cat = missing_per_cat[missing_per_cat > 0].sort_values(ascending=False)

print(missing_per_cat)

term                   0.001460
grade                  0.001460
emp_title              7.387178
emp_length             6.499754
home_ownership         0.001460
verification_status    0.001460
purpose                0.001460
dtype: float64

In [33]:
df_cat['term'].unique()

[' 36 months', ' 60 months', NaN]
Categories (2, object): [' 36 months', ' 60 months']

In [34]:
df_cat['grade'].unique()

['C', 'B', 'F', 'A', 'E', 'D', 'G', NaN]
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [35]:
df_cat['emp_title'].unique()

['leadman', 'Engineer', 'truck driver', 'Information Systems Officer', 'Contract Specialist', ..., 'personal investor', 'OR TECH ', 'Sr. Photo Producer', 'Exec Dir Internal Audit', 'Current Operations Officer']
Length: 512695
Categories (512694, object): ['\tCFO', '\tMultimedia Supervisor', '\tSlot technician', '\tVP - Operations', ..., '​Financial Analyst', '​License Compliance Investigator', '​Senior IT Field Support', '👨‍🍳 ']

In [36]:
df_cat['emp_length'].unique()

['10+ years', '3 years', '4 years', '6 years', '1 year', ..., '5 years', '2 years', '9 years', '< 1 year', NaN]
Length: 12
Categories (11, object): ['1 year', '10+ years', '2 years', '3 years', ..., '7 years', '8 years', '9 years', '< 1 year']

In [37]:
df_cat['home_ownership'].unique()

['MORTGAGE', 'RENT', 'OWN', 'ANY', NaN, 'NONE', 'OTHER']
Categories (6, object): ['ANY', 'MORTGAGE', 'NONE', 'OTHER', 'OWN', 'RENT']

In [39]:
df_cat['verification_status'].unique()

['Not Verified', 'Source Verified', 'Verified', NaN]
Categories (3, object): ['Not Verified', 'Source Verified', 'Verified']

In [44]:
df_cat['purpose'].unique()

['debt_consolidation', 'small_business', 'home_improvement', 'major_purchase', 'credit_card', ..., 'moving', 'renewable_energy', 'wedding', 'educational', NaN]
Length: 15
Categories (14, object): ['car', 'credit_card', 'debt_consolidation', 'educational', ..., 'renewable_energy', 'small_business', 'vacation', 'wedding']

In [45]:
df_cat['purpose'].unique()

['debt_consolidation', 'small_business', 'home_improvement', 'major_purchase', 'credit_card', ..., 'moving', 'renewable_energy', 'wedding', 'educational', NaN]
Length: 15
Categories (14, object): ['car', 'credit_card', 'debt_consolidation', 'educational', ..., 'renewable_energy', 'small_business', 'vacation', 'wedding']

In [43]:
df_purpose_unique = pd.DataFrame(df_cat['purpose'].unique())
df_purpose_unique

                     0
0   debt_consolidation
1       small_business
2     home_improvement
3       major_purchase
4          credit_card
5                other
6                house
7             vacation
8                  car
9              medical
10              moving
11    renewable_energy
12             wedding
13         educational
14                 NaN

In [ ]:
# 직업 유니크값 텍스트 파일 저장
all_emp_titles = df_cat['emp_title'].unique()

In [ ]:
output_filename = 'emp_title_unique_values.txt'

try:
    all_emp_titles = df_cat['emp_title'].unique() 

    with open(output_filename, 'w', encoding='utf-8') as f:
        f.write("--- 'emp_title' 컬럼의 모든 고유값 ---\n")
        for title in all_emp_titles: 
            f.write(str(title) + '\n') # 각 title을 문자열로 변환하여 저장

    print(f"\n모든 'emp_title' 고유값이 '{output_filename}' 파일에 성공적으로 저장되었습니다.")
    print(f"파일이 저장된 위치: {os.getcwd()}") # 현재 작업 디렉토리 출력

except NameError:
    print("오류: 'all_emp_titles' 변수가 정의되지 않았습니다. df_cat['emp_title'].unique()를 먼저 실행하여 정의해주세요.")
except Exception as e:
    print(f"파일 저장 중 다른 오류가 발생했습니다: {e}")

모든 'emp_title' 고유값이 'emp_title_unique_values.txt' 파일에 성공적으로 저장되었습니다.
오류: 'all_emp_titles' 변수가 정의되지 않았습니다. df_cat['emp_title'].unique()를 먼저 실행하여 정의해주세요.

In [29]:
# 직업 유니크값 csv 파일 저장
df_unique_emp_titles = pd.DataFrame(all_emp_titles, columns=['emp_title'])
df_unique_emp_titles.head()

                     emp_title
0                      leadman
1                     Engineer
2                 truck driver
3  Information Systems Officer
4          Contract Specialist

In [31]:
output_csv_filename = 'emp_title_unique_values.csv'

try:
    df_unique_emp_titles.to_csv(
        output_csv_filename,
        index=False,        # DataFrame의 인덱스를 CSV에 포함하지 않습니다. (기본적으로 0부터 시작하는 숫자 인덱스는 불필요)
        encoding='utf-8-sig' # 한글 깨짐 방지를 위해 'utf-8-sig' (BOM 포함 UTF-8) 사용
    )
    print(f"\n모든 'emp_title' 고유값이 '{output_csv_filename}' 파일에 성공적으로 저장되었습니다.")
    print(f"파일이 저장된 위치: {os.getcwd()}") # 현재 작업 디렉토리 출력

except Exception as e:
    print(f"CSV 파일 저장 중 오류가 발생했습니다: {e}")

모든 'emp_title' 고유값이 'emp_title_unique_values.csv' 파일에 성공적으로 저장되었습니다.
CSV 파일 저장 중 오류가 발생했습니다: name 'os' is not defined

In [15]:
# 직업 컬럼 nan값 제거
df_cat = df_cat.dropna(subset=['emp_title'])

In [18]:
# 소문자 변환 + 앞뒤 공백제거
df_cat.loc[:, 'emp_title'] = df_cat['emp_title'].astype(str).str.lower().str.strip()

# 카테고리형으로 변환
df_cat['emp_title'] = df_cat['emp_title'].astype('category')

C:\Users\user\AppData\Local\Temp\ipykernel_17256\2609559027.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cat['emp_title'] = df_cat['emp_title'].astype('category')

In [21]:
df_cat.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2093699 entries, 0 to 2260698
Data columns (total 7 columns):
 #   Column               Dtype
---  ------               -----
 0   term                 category
 1   grade                category
 2   emp_title            category
 3   emp_length           category
 4   home_ownership       category
 5   verification_status  category
 6   purpose              category
dtypes: category(7)
memory usage: 55.2 MB

In [26]:
# --- 4. 결과 확인 (선택 사항) ---
print("--- 전처리 후 df_cat_no_nan DataFrame 정보 ---")
print(df_cat.info())

print("\n--- 전처리 후 'emp_title' 고유값 상위 20개 ---")
print(df_cat['emp_title'].value_counts().head(20))

print(f"\n'emp_title' 컬럼의 NaN 개수 (제거 후): {df_cat['emp_title'].isnull().sum()}")
print(f"원본 df_cat의 행 수: {df_cat.shape[0]}개")
print(f"NaN 제거 후 df_cat의 행 수: {df_cat.shape[0]}개")

--- 전처리 후 df_cat_no_nan DataFrame 정보 ---
<class 'pandas.core.frame.DataFrame'>
Index: 2093699 entries, 0 to 2260698
Data columns (total 7 columns):
 #   Column               Dtype
---  ------               -----
 0   term                 category
 1   grade                category
 2   emp_title            category
 3   emp_length           category
 4   home_ownership       category
 5   verification_status  category
 6   purpose              category
dtypes: category(7)
memory usage: 55.2 MB
None

--- 전처리 후 'emp_title' 고유값 상위 20개 ---
emp_title
teacher               48460
manager               45852
owner                 33591
registered nurse      23354
supervisor            22306
driver                22267
sales                 18984
rn                    17196
office manager        14231
project manager       13842
general manager       13317
truck driver          12797
director              10595
president              9826
engineer               8978
sales manager          8532
operations manager     8183
police officer         7675
vice president         7625
technician             7437
Name: count, dtype: int64

'emp_title' 컬럼의 NaN 개수 (제거 후): 0
원본 df_cat의 행 수: 2093699개
NaN 제거 후 df_cat의 행 수: 2093699개

In [63]:
# --- 5. NaN 제외하고 빈도수 집계 (상위 20개) ---
# .dropna()를 사용해 NaN을 제외한 후 value_counts()로 빈도수를 집계합니다.
# 출력 옵션 설정 (많은 직업명을 볼 때 유용)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

emp_title_clean_counts = acc_df_cleaned['emp_title_clean'].dropna().value_counts()
print(f"\n전처리된 'emp_title_clean' (NaN 제외) 상위 20개:")
print(emp_title_clean_counts.head(20)) # 동료 코드와 일관성 위해 20개로 수정

전처리된 'emp_title_clean' (NaN 제외) 상위 20개:
emp_title_clean
teacher               48460
manager               45852
owner                 33591
registered nurse      23354
supervisor            22306
driver                22267
sales                 18984
rn                    17196
office manager        14231
project manager       13842
general manager       13317
truck driver          12797
director              10595
president              9826
engineer               8978
sales manager          8532
operations manager     8183
police officer         7675
vice president         7625
technician             7437
Name: count, dtype: int64

In [48]:
top_n = 100 
top_titles = df_cat['emp_title'].value_counts().nlargest(top_n).index

df_cat['emp_title_grouped_freq'] = df_cat['emp_title'].apply(
    lambda x: x if x in top_titles else 'Other'
).astype('category')

# 새로운 컬럼의 고유값 개수 확인
print(df_cat['emp_title_grouped_freq'].nunique())
print(df_cat['emp_title_grouped_freq'].value_counts())

101
emp_title_grouped_freq
Other                       1615090
Teacher                       38824
Manager                       34298
Owner                         21977
Registered Nurse              15867
Driver                        14753
RN                            14737
Supervisor                    14297
Sales                         13050
Project Manager               10971
Office Manager                 9772
General Manager                9251
Director                       8934
owner                          8507
President                      7660
Engineer                       7304
manager                        7060
teacher                        6692
Operations Manager             6128
Vice President                 5874
Accountant                     5596
Sales Manager                  5408
driver                         5386
Attorney                       5365
Administrative Assistant       5270
Nurse                          5189
Truck Driver                   4911
Account Manager                4727
Police Officer                 4572
Technician                     4525
Analyst                        4238
Executive Assistant            4161
Server                         4121
Store Manager                  4088
sales                          3876
Mechanic                       3724
Paralegal                      3699
Software Engineer              3635
supervisor                     3586
Supervisor                     3354
CEO                            3350
Controller                     3325
Assistant Manager              3269
Consultant                     3247
Program Manager                3237
Branch Manager                 3166
Foreman                        3089
truck driver                   3020
Administrator                  2997
Electrician                    2996
Registered nurse               2865
Principal                      2831
Truck driver                   2771
Manager                        2669
Operator                       2657
Business Analyst               2617
Account Executive              2597
Executive Director             2551
Professor                      2484
IT Manager                     2483
Customer Service               2372
Clerk                          2304
Director of Operations         2222
LPN                            2215
Bartender                      2165
Teacher                        2115
Associate                      2063
Superintendent                 2052
registered nurse               2035
Secretary                      2033
Legal Assistant                2011
District Manager               1971
Physician                      1949
CNA                            1921
Maintenance                    1883
Financial Advisor              1880
Machinist                      1874
Pharmacist                     1840
Cashier                        1821
Officer                        1820
mechanic                       1815
Laborer                        1799
Realtor                        1774
Partner                        1769
Accounting Manager             1743
Financial Analyst              1743
Bookkeeper                     1706
Senior Manager                 1690
Social Worker                  1649
Service Manager                1631
Welder                         1620
Property Manager               1595
Instructor                     1590
Production Manager             1564
Owner                          1562
Cook                           1560
Firefighter                    1552
Underwriter                    1535
Sales Associate                1526
Software Developer             1522
Nurse Practitioner             1510
Name: count, dtype: int64

In [27]:
import re # 정규표현식

In [ ]:
job_keywords = [
    'engineer', 'manager', 'driver', 'teacher', 'analyst',
    'specialist', 'assistant', 'technician', 'sales', 'clerk',
    'developer', 'nurse', 'attorney', 'accountant', 'consultant',
    'coordinator', 'representative', 'supervisor', 'admin', 'operator',
    'director', 'medical', 'finance', 'architect', 'researcher',
    'advisor', 'designer', 'mechanic', 'electrician', 'welder',
    'marketing', 'production', 'training', 'officer', 'business',
    'owner', 'partner', 'president', 'vp'#부사장, 'executive',
    'intern', 'student', 'retired', 'other' # 'other'는 특별 처리할 용도
]

In [ ]:
grouped_emp_title = df_cat['emp_title'].copy()
grouped_emp_title = grouped_emp_title.cat.add_categories(['Other']) # other 카테고리 추가

In [41]:
# 'rn'이 포함되면 무조건 'nurse'로 먼저 처리 (최우선 순위)
rn_condition = grouped_emp_title.str.contains('rn', na=False)
grouped_emp_title.loc[rn_condition] = 'nurse'

In [42]:
for keyword in job_keywords:
    condition = grouped_emp_title.str.contains(keyword, na=False)
    grouped_emp_title.loc[condition] = keyword # 조건에 맞는 값을 키워드로 업데이트

grouped_emp_title[~grouped_emp_title.isin(job_keywords + ['nurse'])] = 'Other'

# 원래 컬럼에 덮어 쓰기
df_cat['emp_title'] = grouped_emp_title.astype('category')

C:\Users\user\AppData\Local\Temp\ipykernel_17256\2107620401.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cat['emp_title'] = grouped_emp_title.astype('category')

In [43]:
# --- 4. 그룹화 결과 확인 ---
print(f"--- 'emp_title' 컬럼 그룹화 결과 ---")
print(f"그룹화 후 'emp_title' 고유값 개수: {df_cat['emp_title'].nunique()}개")
print("\n'emp_title' 컬럼의 상위 빈도 목록:")
print(df_cat['emp_title'].value_counts().head(20))

print("\n'emp_title' 컬럼의 하위 빈도 목록:")
print(df_cat['emp_title'].value_counts().tail(10))

# 'nurse' 및 'Other' 카테고리 포함 확인
print("\n'nurse' 카테고리 빈도:")
if 'nurse' in df_cat['emp_title'].cat.categories:
    print(df_cat['emp_title'].value_counts()['nurse'])
else:
    print("'nurse' 카테고리 없음.")

print("\n'Other' 카테고리 빈도:")
if 'Other' in df_cat['emp_title'].cat.categories:
    print(df_cat['emp_title'].value_counts()['Other'])
else:
    print("'Other' 카테고리 없음.")

--- 'emp_title' 컬럼 그룹화 결과 ---
그룹화 후 'emp_title' 고유값 개수: 43개

'emp_title' 컬럼의 상위 빈도 목록:
emp_title
Other          774707
manager        305184
nurse           92518
director        71735
engineer        59756
teacher         59279
assistant       58912
supervisor      57069
sales           55260
specialist      54849
driver          52557
analyst         51198
technician      40836
officer         39869
owner           39307
admin           31411
operator        31339
coordinator     30639
president       24645
consultant      18296
Name: count, dtype: int64

'emp_title' 컬럼의 하위 빈도 목록:
emp_title
zytron control products, inc.               0
{owner}truck driver                         0
| principal business solution architect|    0
år.  technical illustrator                 0
​associate tech support analyst             0
​financial analyst                          0
​license compliance investigator            0
​senior it field support                    0
👨‍🍳                                         0
substitute teacher/paraprofessional         0
Name: count, dtype: int64

'nurse' 카테고리 빈도:
92518

'Other' 카테고리 빈도:
774707

In [45]:
professional_level_mapping = {
    # --- 전문직 (Professional) ---
    # 높은 수준의 교육, 특정 자격/면허, 전문 지식을 요구하는 직업군
    'engineer': 'Professional',
    'analyst': 'Professional',
    'developer': 'Professional',
    'attorney': 'Professional',
    'accountant': 'Professional',
    'consultant': 'Professional',
    'architect': 'Professional',
    'researcher': 'Professional',
    'advisor': 'Professional',
    'designer': 'Professional', # UX/UI, 산업 디자이너 등 전문성 강조
    'nurse': 'Professional',
    'medical': 'Professional', # 의료 전문가 (의사, 약사 등)
    'teacher': 'Professional',
    'finance': 'Professional', # 금융 전문직 (재무 분석가, 포트폴리오 매니저 등)

    # --- 관리직 (Management) ---
    # 전문직에 속할 수도 있지만, 대규모 조직 관리 역할에 중점을 둠.
    # 경우에 따라 'Professional' 또는 별도 'Management' 카테고리로 분류 가능.
    'manager': 'Management', # 매니저는 비전문직 카테고리로 들어갈 수도 있습니다.
                              # 'Manager'는 넓은 의미를 가지므로, 다른 전문직 매니저를 구분하기 어렵습니다.
                              # 예를 들어 IT 매니저는 전문직 매니저이지만, 매장 매니저는 비전문직으로 분류될 수도 있습니다.
                              # 여기서는 관리/리더십 역할로 분류했습니다.
    'supervisor': 'Management',
    'coordinator': 'Management',
    'director': 'Management',
    'officer': 'Management', # CEO, CFO 등 C-level 임원 포함
    'president': 'Management',
    'vp': 'Management', # 부사장
    'executive': 'Management', # 임원
    'owner': 'Management', # 사업체 소유주 (자영업 포함)
    'partner': 'Management', # 동업자

    # --- 비전문직 (Non-Professional) ---
    # 상대적으로 진입 장벽이 낮거나, 실무 중심의 직업군
    'driver': 'Non-Professional',
    'specialist': 'Non-Professional', # 'IT Specialist' 등은 전문직일 수 있지만, 넓은 의미의 specialist는 비전문직에 포함될 수 있습니다.
                                    # 여기서는 명확한 전문성이 부여되지 않은 경우로 분류합니다.
    'assistant': 'Non-Professional',
    'technician': 'Non-Professional',
    'sales': 'Non-Professional',
    'clerk': 'Non-Professional',
    'admin': 'Non-Professional', # 관리직 (Manager)와 혼동 주의. 여기서는 Administrative Assistant 등에 가까움.
    'operator': 'Non-Professional', # 기계 오퍼레이터 등
    'marketing': 'Non-Professional', # 마케팅은 전문직일 수 있으나, Sales와 유사하게 일부 비전문직 영역 존재
    'production': 'Non-Professional',
    'training': 'Non-Professional',
    'business': 'Non-Professional', # 'Business Owner'와 달리, 'Business Assistant' 등
    'mechanic': 'Non-Professional',
    'electrician': 'Non-Professional',
    'welder': 'Non-Professional',

    # --- 기타/학생/은퇴 (Other / Student / Retired) ---
    'intern': 'Other', # 인턴 (아직 정식 직업인이라 보기 어려움)
    'student': 'Other', # 학생
    'retired': 'Other', # 은퇴자
    'other': 'Other',   # 이전 단계에서 그룹화되지 않은 모든 직업
}

In [49]:
# --- 'emp_title_professional_level' 컬럼 생성 ---
df_cat['emp_title_professional_level'] = df_cat['emp_title'].map(professional_level_mapping)

# get() 메서드를 사용하여 딕셔너리에 없는 키가 나오면 기본값으로 'Other'를 반환합니다.
df_cat['emp_title_professional_level'] = df_cat['emp_title'].apply(
    lambda x: professional_level_mapping.get(x, 'Other')
)

# 최종 컬럼을 category 타입으로 변환
df_cat['emp_title_professional_level'] = df_cat['emp_title_professional_level'].astype('category')


# --- 결과 확인 ---
print("--- 'emp_title_professional_level' 컬럼의 빈도 ---")
print(df_cat['emp_title_professional_level'].value_counts())

print(f"\n새로운 그룹화 컬럼의 고유값 개수: {df_cat['emp_title_professional_level'].nunique()}개")

C:\Users\user\AppData\Local\Temp\ipykernel_17256\127733864.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cat['emp_title_professional_level'] = df_cat['emp_title'].map(professional_level_mapping)

--- 'emp_title_professional_level' 컬럼의 빈도 ---
emp_title_professional_level
Other               784707
Management          591783
Non-Professional    381031
Professional        336178
Name: count, dtype: int64

새로운 그룹화 컬럼의 고유값 개수: 4개

C:\Users\user\AppData\Local\Temp\ipykernel_17256\127733864.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cat['emp_title_professional_level'] = df_cat['emp_title'].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_17256\127733864.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cat['emp_title_professional_level'] = df_cat['emp_title_professional_level'].astype('category')

In [50]:
df_cat.head()

,term,grade,emp_title,emp_length,home_ownership,verification_status,purpose,emp_title_professional_level
0,36 months,C,Other,10+ years,MORTGAGE,Not Verified,debt_consolidation,Other
1,36 months,C,engineer,10+ years,MORTGAGE,Not Verified,small_business,Professional
2,60 months,B,driver,10+ years,MORTGAGE,Not Verified,home_improvement,Non-Professional
3,60 months,C,officer,10+ years,MORTGAGE,Source Verified,debt_consolidation,Management
4,60 months,F,specialist,3 years,MORTGAGE,Source Verified,major_purchase,Non-Professional

# 범주형 데이터 결측치 처리

In [52]:
# 결측치 확인
nan_rows_term_idx = acc_df_cleaned[acc_df_cleaned['term'].isnull()].index

print(f"term 컬럼에 NaN이 있는 {len(nan_rows_term_idx)}개 행의 'loan_status' 분포:")
# 해당 행들의 loan_status 값들을 확인합니다.
# acc_df_cleaned에 loan_status 컬럼이 있다고 가정합니다.
if 'loan_status' in acc_df_cleaned.columns:
    print(acc_df_cleaned.loc[nan_rows_term_idx, 'loan_status'].value_counts(dropna=False))
else:
    print("acc_df_cleaned에 'loan_status' 컬럼이 없어 직접 확인 불가합니다.")

term 컬럼에 NaN이 있는 33개 행의 'loan_status' 분포:
loan_status
NaN    33
Name: count, dtype: int64

In [53]:
# 'term' 컬럼과 'grade' 컬럼의 결측치가 동일한 행에 있는지 확인
are_same_nan_rows = acc_df_cleaned['term'].isnull() == acc_df_cleaned['grade'].isnull()
# 모든 값이 True여야 동일한 행에 결측치가 있다는 뜻입니다.
print(f"\n'term'과 'grade' 컬럼의 결측치가 동일한 행에 있는지 여부: {are_same_nan_rows.all()}")

# 모든 33개 NaN 컬럼에 대해 동시에 NaN인지 확인
# df_cat에는 'term', 'grade', 'home_ownership', 'verification_status', 'purpose'가 포함되어 있습니다.
# acc_df_cleaned에서 이 컬럼들의 NaN 상태를 가져옵니다.
combined_nan_condition = (acc_df_cleaned['term'].isnull() &
                          acc_df_cleaned['grade'].isnull() &
                          acc_df_cleaned['home_ownership'].isnull() &
                          acc_df_cleaned['verification_status'].isnull() &
                          acc_df_cleaned['purpose'].isnull())

# 이 조건에 해당하는 행의 개수
print(f"\n모든 5개 컬럼이 동시에 NaN인 행의 개수: {combined_nan_condition.sum()}개")

# 이 값이 33개와 일치한다면, 그 33개의 행이 5개 컬럼 모두에서 동시에 결측값을 가집니다.
# 이는 해당 33개 행의 특성을 살펴보는 것이 문제 해결에 중요함을 시사합니다.
# 이 행들의 다른 컬럼들 (예: loan_amnt, issue_d 등)의 분포를 확인해 볼 수 있습니다.

'term'과 'grade' 컬럼의 결측치가 동일한 행에 있는지 여부: True

모든 5개 컬럼이 동시에 NaN인 행의 개수: 33개

In [ ]:
# 모든 5개 컬럼이 동시에 NaN인 조건을 정의
nan_condition_for_33_rows = (acc_df_cleaned['term'].isnull() &
                             acc_df_cleaned['grade'].isnull() &
                             acc_df_cleaned['home_ownership'].isnull() &
                             acc_df_cleaned['verification_status'].isnull() &
                             acc_df_cleaned['purpose'].isnull())

In [57]:
# acc_df_cleaned에서 이 33개의 행을 추출합니다.
df_33_nan_rows = acc_df_cleaned[nan_condition_for_33_rows]

# --- 3. 선택된 행들의 모든 컬럼을 출력합니다. ---
# Pandas의 출력 옵션을 조정하여 모든 컬럼과 행을 볼 수 있도록 합니다.
pd.set_option('display.max_rows', None)       # 모든 행 표시 (33개라 많지 않음)
pd.set_option('display.max_columns', None)    # 모든 컬럼 표시
pd.set_option('display.width', None)          # 콘솔 너비 제한 없음
pd.set_option('display.max_colwidth', None)   # 컬럼 내용 잘림 방지

print("--- 5개 컬럼이 동시에 NaN인 33개 행의 데이터 ---")
print(df_33_nan_rows)

--- 5개 컬럼이 동시에 NaN인 33개 행의 데이터 ---
                                                       id  loan_amnt  \
421095   Total amount funded in policy code 1: 6417608175        NaN
421096   Total amount funded in policy code 2: 1944088810        NaN
528961   Total amount funded in policy code 1: 1741781700        NaN
528962    Total amount funded in policy code 2: 564202131        NaN
651664   Total amount funded in policy code 1: 1791201400        NaN
651665    Total amount funded in policy code 2: 651669342        NaN
749520   Total amount funded in policy code 1: 1443412975        NaN
749521    Total amount funded in policy code 2: 511988838        NaN
877716   Total amount funded in policy code 1: 2063142975        NaN
877717    Total amount funded in policy code 2: 823319310        NaN
983169   Total amount funded in policy code 1: 1538432075        NaN
983170    Total amount funded in policy code 2: 608903141        NaN
1117058  Total amount funded in policy code 1: 2087217200        NaN
1117059   Total amount funded in policy code 2: 662815446        NaN
1352689  Total amount funded in policy code 1: 3503840175        NaN
1352690   Total amount funded in policy code 2: 873652739        NaN
1481103  Total amount funded in policy code 1: 2050909275        NaN
1481104   Total amount funded in policy code 2: 820109297        NaN
1611877  Total amount funded in policy code 1: 2080429200        NaN
1611878   Total amount funded in policy code 2: 737901574        NaN
1651665          Loans that do not meet the credit policy        NaN
1654415   Total amount funded in policy code 1: 460296150        NaN
1654416           Total amount funded in policy code 2: 0        NaN
1751196  Total amount funded in policy code 1: 1437969475        NaN
1751197   Total amount funded in policy code 2: 520780182        NaN
1939379  Total amount funded in policy code 1: 2700702175        NaN
1939380    Total amount funded in policy code 2: 81866225        NaN
2038501  Total amount funded in policy code 1: 1404586950        NaN
2038502   Total amount funded in policy code 2: 567447023        NaN
2157151  Total amount funded in policy code 1: 1817354125        NaN
2157152   Total amount funded in policy code 2: 620899600        NaN
2260699  Total amount funded in policy code 1: 1465324575        NaN
2260700   Total amount funded in policy code 2: 521953170        NaN

         funded_amnt  funded_amnt_inv term  int_rate  installment grade  \
421095           NaN              NaN  NaN       NaN          NaN   NaN
421096           NaN              NaN  NaN       NaN          NaN   NaN
528961           NaN              NaN  NaN       NaN          NaN   NaN
528962           NaN              NaN  NaN       NaN          NaN   NaN
651664           NaN              NaN  NaN       NaN          NaN   NaN
651665           NaN              NaN  NaN       NaN          NaN   NaN
749520           NaN              NaN  NaN       NaN          NaN   NaN
749521           NaN              NaN  NaN       NaN          NaN   NaN
877716           NaN              NaN  NaN       NaN          NaN   NaN
877717           NaN              NaN  NaN       NaN          NaN   NaN
983169           NaN              NaN  NaN       NaN          NaN   NaN
983170           NaN              NaN  NaN       NaN          NaN   NaN
1117058          NaN              NaN  NaN       NaN          NaN   NaN
1117059          NaN              NaN  NaN       NaN          NaN   NaN
1352689          NaN              NaN  NaN       NaN          NaN   NaN
1352690          NaN              NaN  NaN       NaN          NaN   NaN
1481103          NaN              NaN  NaN       NaN          NaN   NaN
1481104          NaN              NaN  NaN       NaN          NaN   NaN
1611877          NaN              NaN  NaN       NaN          NaN   NaN
1611878          NaN              NaN  NaN       NaN          NaN   NaN
1651665          NaN              NaN  NaN       NaN          NaN   NaN
1654415          NaN              NaN  NaN       NaN          NaN   NaN
1654416          NaN              NaN  NaN       NaN          NaN   NaN
1751196          NaN              NaN  NaN       NaN          NaN   NaN
1751197          NaN              NaN  NaN       NaN          NaN   NaN
1939379          NaN              NaN  NaN       NaN          NaN   NaN
1939380          NaN              NaN  NaN       NaN          NaN   NaN
2038501          NaN              NaN  NaN       NaN          NaN   NaN
2038502          NaN              NaN  NaN       NaN          NaN   NaN
2157151          NaN              NaN  NaN       NaN          NaN   NaN
2157152          NaN              NaN  NaN       NaN          NaN   NaN
2260699          NaN              NaN  NaN       NaN          NaN   NaN
2260700          NaN              NaN  NaN       NaN          NaN   NaN

        sub_grade emp_title emp_length home_ownership  annual_inc  \
421095        NaN       NaN        NaN            NaN         NaN
421096        NaN       NaN        NaN            NaN         NaN
528961        NaN       NaN        NaN            NaN         NaN
528962        NaN       NaN        NaN            NaN         NaN
651664        NaN       NaN        NaN            NaN         NaN
651665        NaN       NaN        NaN            NaN         NaN
749520        NaN       NaN        NaN            NaN         NaN
749521        NaN       NaN        NaN            NaN         NaN
877716        NaN       NaN        NaN            NaN         NaN
877717        NaN       NaN        NaN            NaN         NaN
983169        NaN       NaN        NaN            NaN         NaN
983170        NaN       NaN        NaN            NaN         NaN
1117058       NaN       NaN        NaN            NaN         NaN
1117059       NaN       NaN        NaN            NaN         NaN
1352689       NaN       NaN        NaN            NaN         NaN
1352690       NaN       NaN        NaN            NaN         NaN
1481103       NaN       NaN        NaN            NaN         NaN
1481104       NaN       NaN        NaN            NaN         NaN
1611877       NaN       NaN        NaN            NaN         NaN
1611878       NaN       NaN        NaN            NaN         NaN
1651665       NaN       NaN        NaN            NaN         NaN
1654415       NaN       NaN        NaN            NaN         NaN
1654416       NaN       NaN        NaN            NaN         NaN
1751196       NaN       NaN        NaN            NaN         NaN
1751197       NaN       NaN        NaN            NaN         NaN
1939379       NaN       NaN        NaN            NaN         NaN
1939380       NaN       NaN        NaN            NaN         NaN
2038501       NaN       NaN        NaN            NaN         NaN
2038502       NaN       NaN        NaN            NaN         NaN
2157151       NaN       NaN        NaN            NaN         NaN
2157152       NaN       NaN        NaN            NaN         NaN
2260699       NaN       NaN        NaN            NaN         NaN
2260700       NaN       NaN        NaN            NaN         NaN

        verification_status issue_d loan_status pymnt_plan  url purpose title  \
421095                  NaN     NaN         NaN        NaN  NaN     NaN   NaN
421096                  NaN     NaN         NaN        NaN  NaN     NaN   NaN
528961                  NaN     NaN         NaN        NaN  NaN     NaN   NaN
528962                  NaN     NaN         NaN        NaN  NaN     NaN   NaN
651664                  NaN     NaN         NaN        NaN  NaN     NaN   NaN
651665                  NaN     NaN         NaN        NaN  NaN     NaN   NaN
749520                  NaN     NaN         NaN        NaN  NaN     NaN   NaN
749521                  NaN     NaN         NaN        NaN  NaN     NaN   NaN
877716                  NaN     NaN         NaN        NaN  NaN     NaN   NaN
877717                  NaN     NaN         NaN        NaN  NaN     NaN   NaN
983169                  NaN     NaN         NaN        NaN  NaN     NaN   NaN
983170                  NaN     NaN         NaN        NaN  NaN     NaN   NaN
1117058                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
1117059                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
1352689                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
1352690                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
1481103                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
1481104                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
1611877                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
1611878                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
1651665                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
1654415                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
1654416                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
1751196                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
1751197                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
1939379                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
1939380                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
2038501                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
2038502                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
2157151                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
2157152                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
2260699                 NaN     NaN         NaN        NaN  NaN     NaN   NaN
2260700                 NaN     NaN         NaN        NaN  NaN     NaN   NaN

        zip_code addr_state  dti  delinq_2yrs earliest_cr_line  \
421095       NaN        NaN  NaN          NaN              NaN
421096       NaN        NaN  NaN          NaN              NaN
528961       NaN        NaN  NaN          NaN              NaN
528962       NaN        NaN  NaN          NaN              NaN
651664       NaN        NaN  NaN          NaN              NaN
651665       NaN        NaN  NaN          NaN              NaN
749520       NaN        NaN  NaN          NaN              NaN
749521       NaN        NaN  NaN          NaN              NaN
877716       NaN        NaN  NaN          NaN              NaN
877717       NaN        NaN  NaN          NaN              NaN
983169       NaN        NaN  NaN          NaN              NaN
983170       NaN        NaN  NaN          NaN              NaN
1117058      NaN        NaN  NaN          NaN              NaN
1117059      NaN        NaN  NaN          NaN              NaN
1352689      NaN        NaN  NaN          NaN              NaN
1352690      NaN        NaN  NaN          NaN              NaN
1481103      NaN        NaN  NaN          NaN              NaN
1481104      NaN        NaN  NaN          NaN              NaN
1611877      NaN        NaN  NaN          NaN              NaN
1611878      NaN        NaN  NaN          NaN              NaN
1651665      NaN        NaN  NaN          NaN              NaN
1654415      NaN        NaN  NaN          NaN              NaN
1654416      NaN        NaN  NaN          NaN              NaN
1751196      NaN        NaN  NaN          NaN              NaN
1751197      NaN        NaN  NaN          NaN              NaN
1939379      NaN        NaN  NaN          NaN              NaN
1939380      NaN        NaN  NaN          NaN              NaN
2038501      NaN        NaN  NaN          NaN              NaN
2038502      NaN        NaN  NaN          NaN              NaN
2157151      NaN        NaN  NaN          NaN              NaN
2157152      NaN        NaN  NaN          NaN              NaN
2260699      NaN        NaN  NaN          NaN              NaN
2260700      NaN        NaN  NaN          NaN              NaN

         fico_range_low  fico_range_high  inq_last_6mths  \
421095              NaN              NaN             NaN
421096              NaN              NaN             NaN
528961              NaN              NaN             NaN
528962              NaN              NaN             NaN
651664              NaN              NaN             NaN
651665              NaN              NaN             NaN
749520              NaN              NaN             NaN
749521              NaN              NaN             NaN
877716              NaN              NaN             NaN
877717              NaN              NaN             NaN
983169              NaN              NaN             NaN
983170              NaN              NaN             NaN
1117058             NaN              NaN             NaN
1117059             NaN              NaN             NaN
1352689             NaN              NaN             NaN
1352690             NaN              NaN             NaN
1481103             NaN              NaN             NaN
1481104             NaN              NaN             NaN
1611877             NaN              NaN             NaN
1611878             NaN              NaN             NaN
1651665             NaN              NaN             NaN
1654415             NaN              NaN             NaN
1654416             NaN              NaN             NaN
1751196             NaN              NaN             NaN
1751197             NaN              NaN             NaN
1939379             NaN              NaN             NaN
1939380             NaN              NaN             NaN
2038501             NaN              NaN             NaN
2038502             NaN              NaN             NaN
2157151             NaN              NaN             NaN
2157152             NaN              NaN             NaN
2260699             NaN              NaN             NaN
2260700             NaN              NaN             NaN

         mths_since_last_delinq  open_acc  pub_rec  revol_bal  revol_util  \
421095                      NaN       NaN      NaN        NaN         NaN
421096                      NaN       NaN      NaN        NaN         NaN
528961                      NaN       NaN      NaN        NaN         NaN
528962                      NaN       NaN      NaN        NaN         NaN
651664                      NaN       NaN      NaN        NaN         NaN
651665                      NaN       NaN      NaN        NaN         NaN
749520                      NaN       NaN      NaN        NaN         NaN
749521                      NaN       NaN      NaN        NaN         NaN
877716                      NaN       NaN      NaN        NaN         NaN
877717                      NaN       NaN      NaN        NaN         NaN
983169                      NaN       NaN      NaN        NaN         NaN
983170                      NaN       NaN      NaN        NaN         NaN
1117058                     NaN       NaN      NaN        NaN         NaN
1117059                     NaN       NaN      NaN        NaN         NaN
1352689                     NaN       NaN      NaN        NaN         NaN
1352690                     NaN       NaN      NaN        NaN         NaN
1481103                     NaN       NaN      NaN        NaN         NaN
1481104                     NaN       NaN      NaN        NaN         NaN
1611877                     NaN       NaN      NaN        NaN         NaN
1611878                     NaN       NaN      NaN        NaN         NaN
1651665                     NaN       NaN      NaN        NaN         NaN
1654415                     NaN       NaN      NaN        NaN         NaN
1654416                     NaN       NaN      NaN        NaN         NaN
1751196                     NaN       NaN      NaN        NaN         NaN
1751197                     NaN       NaN      NaN        NaN         NaN
1939379                     NaN       NaN      NaN        NaN         NaN
1939380                     NaN       NaN      NaN        NaN         NaN
2038501                     NaN       NaN      NaN        NaN         NaN
2038502                     NaN       NaN      NaN        NaN         NaN
2157151                     NaN       NaN      NaN        NaN         NaN
2157152                     NaN       NaN      NaN        NaN         NaN
2260699                     NaN       NaN      NaN        NaN         NaN
2260700                     NaN       NaN      NaN        NaN         NaN

         total_acc initial_list_status  out_prncp  out_prncp_inv  total_pymnt  \
421095         NaN                 NaN        NaN            NaN          NaN
421096         NaN                 NaN        NaN            NaN          NaN
528961         NaN                 NaN        NaN            NaN          NaN
528962         NaN                 NaN        NaN            NaN          NaN
651664         NaN                 NaN        NaN            NaN          NaN
651665         NaN                 NaN        NaN            NaN          NaN
749520         NaN                 NaN        NaN            NaN          NaN
749521         NaN                 NaN        NaN            NaN          NaN
877716         NaN                 NaN        NaN            NaN          NaN
877717         NaN                 NaN        NaN            NaN          NaN
983169         NaN                 NaN        NaN            NaN          NaN
983170         NaN                 NaN        NaN            NaN          NaN
1117058        NaN                 NaN        NaN            NaN          NaN
1117059        NaN                 NaN        NaN            NaN          NaN
1352689        NaN                 NaN        NaN            NaN          NaN
1352690        NaN                 NaN        NaN            NaN          NaN
1481103        NaN                 NaN        NaN            NaN          NaN
1481104        NaN                 NaN        NaN            NaN          NaN
1611877        NaN                 NaN        NaN            NaN          NaN
1611878        NaN                 NaN        NaN            NaN          NaN
1651665        NaN                 NaN        NaN            NaN          NaN
1654415        NaN                 NaN        NaN            NaN          NaN
1654416        NaN                 NaN        NaN            NaN          NaN
1751196        NaN                 NaN        NaN            NaN          NaN
1751197        NaN                 NaN        NaN            NaN          NaN
1939379        NaN                 NaN        NaN            NaN          NaN
1939380        NaN                 NaN        NaN            NaN          NaN
2038501        NaN                 NaN        NaN            NaN          NaN
2038502        NaN                 NaN        NaN            NaN          NaN
2157151        NaN                 NaN        NaN            NaN          NaN
2157152        NaN                 NaN        NaN            NaN          NaN
2260699        NaN                 NaN        NaN            NaN          NaN
2260700        NaN                 NaN        NaN            NaN          NaN

         total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  \
421095               NaN              NaN            NaN                 NaN
421096               NaN              NaN            NaN                 NaN
528961               NaN              NaN            NaN                 NaN
528962               NaN              NaN            NaN                 NaN
651664               NaN              NaN            NaN                 NaN
651665               NaN              NaN            NaN                 NaN
749520               NaN              NaN            NaN                 NaN
749521               NaN              NaN            NaN                 NaN
877716               NaN              NaN            NaN                 NaN
877717               NaN              NaN            NaN                 NaN
983169               NaN              NaN            NaN                 NaN

In [58]:
# 'id' 컬럼에 'Total amount funded' 문자열이 포함된 행을 찾습니다.
# na=False는 NaN 값을 False로 처리하여 포함하지 않게 합니다.
# case=False는 대소문자 구분 없이 찾습니다.
metadata_row = acc_df_cleaned['id'].astype(str).str.contains('Total amount funded', na=False, case=False)

print(f"식별된 메타데이터 행의 개수: {metadata_row.sum()}개")

# --- 2. 해당 행들을 DataFrame에서 제거 ---
# 이 불필요한 행들을 제외한 새로운 DataFrame을 생성합니다.
# '~' (틸다)는 조건의 반대(True인 것을 False로, False인 것을 True로)를 의미합니다.
acc_df_cleaned_after_str_contains = acc_df_cleaned[~metadata_row].copy()

print(f"원본 acc_df_cleaned 행 수: {acc_df_cleaned.shape[0]}개")
print(f"`str.contains()` 후 acc_df_cleaned_after_str_contains 행 수: {acc_df_cleaned_after_str_contains.shape[0]}개")

# 제거 후의 결측치 상태 확인 (제거되었음을 확인)
target_nan_cols_to_check = ['term', 'grade', 'home_ownership', 'verification_status', 'purpose']
print("\n--- `str.contains()` 후 주요 컬럼의 결측치 개수 재확인 ---")
print(acc_df_cleaned_after_str_contains[target_nan_cols_to_check].isnull().sum())

식별된 메타데이터 행의 개수: 32개
원본 acc_df_cleaned 행 수: 2260701개
`str.contains()` 후 acc_df_cleaned_after_str_contains 행 수: 2260669개

--- `str.contains()` 후 주요 컬럼의 결측치 개수 재확인 ---
term                   1
grade                  1
home_ownership         1
verification_status    1
purpose                1
dtype: int64

In [ ]:
remaining_nan_row = acc_df_cleaned_after_str_contains[acc_df_cleaned_after_str_contains['term'].isnull()]
print(remaining_nan_row)

                                               id  loan_amnt  funded_amnt  \
1651665  Loans that do not meet the credit policy        NaN          NaN

         funded_amnt_inv term  int_rate  installment grade sub_grade  \
1651665              NaN  NaN       NaN          NaN   NaN       NaN

        emp_title emp_length home_ownership  annual_inc verification_status  \
1651665       NaN        NaN            NaN         NaN                 NaN

        issue_d loan_status pymnt_plan  url purpose title zip_code addr_state  \
1651665     NaN         NaN        NaN  NaN     NaN   NaN      NaN        NaN

         dti  delinq_2yrs earliest_cr_line  fico_range_low  fico_range_high  \
1651665  NaN          NaN              NaN             NaN              NaN

         inq_last_6mths  mths_since_last_delinq  open_acc  pub_rec  revol_bal  \
1651665             NaN                     NaN       NaN      NaN        NaN

         revol_util  total_acc initial_list_status  out_prncp  out_prncp_inv  \
1651665         NaN        NaN                 NaN        NaN            NaN

         total_pymnt  total_pymnt_inv  total_rec_prncp  total_rec_int  \
1651665          NaN              NaN              NaN            NaN

         total_rec_late_fee  recoveries  collection_recovery_fee last_pymnt_d  \
1651665                 NaN         NaN                      NaN          NaN

         last_pymnt_amnt next_pymnt_d last_credit_pull_d  \
1651665              NaN          NaN                NaN

         last_fico_range_high  last_fico_range_low  \
1651665                   NaN                  NaN

         collections_12_mths_ex_med  mths_since_last_major_derog  policy_code  \
1651665                         NaN                          NaN          NaN

        application_type  acc_now_delinq  tot_coll_amt  tot_cur_bal  \
1651665              NaN             NaN           NaN          NaN

         open_acc_6m  open_act_il  open_il_12m  open_il_24m  \
1651665          NaN          NaN          NaN          NaN

         mths_since_rcnt_il  total_bal_il  il_util  open_rv_12m  open_rv_24m  \
1651665                 NaN           NaN      NaN          NaN          NaN

         max_bal_bc  all_util  total_rev_hi_lim  inq_fi  total_cu_tl  \
1651665         NaN       NaN               NaN     NaN          NaN

         inq_last_12m  acc_open_past_24mths  avg_cur_bal  bc_open_to_buy  \
1651665           NaN                   NaN          NaN             NaN

         bc_util  chargeoff_within_12_mths  delinq_amnt  mo_sin_old_il_acct  \
1651665      NaN                       NaN          NaN                 NaN

         mo_sin_old_rev_tl_op  mo_sin_rcnt_rev_tl_op  mo_sin_rcnt_tl  \
1651665                   NaN                    NaN             NaN

         mort_acc  mths_since_recent_bc  mths_since_recent_bc_dlq  \
1651665       NaN                   NaN                       NaN

         mths_since_recent_inq  mths_since_recent_revol_delinq  \
1651665                    NaN                             NaN

         num_accts_ever_120_pd  num_actv_bc_tl  num_actv_rev_tl  num_bc_sats  \
1651665                    NaN             NaN              NaN          NaN

         num_bc_tl  num_il_tl  num_op_rev_tl  num_rev_accts  \
1651665        NaN        NaN            NaN            NaN

         num_rev_tl_bal_gt_0  num_sats  num_tl_120dpd_2m  num_tl_30dpd  \
1651665                  NaN       NaN               NaN           NaN

         num_tl_90g_dpd_24m  num_tl_op_past_12m  pct_tl_nvr_dlq  \
1651665                 NaN                 NaN             NaN

         percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  tot_hi_cred_lim  \
1651665               NaN                   NaN        NaN              NaN

         total_bal_ex_mort  total_bc_limit  total_il_high_credit_limit  \
1651665                NaN             NaN                         NaN

        hardship_flag disbursement_method debt_settlement_flag
1651665           NaN                 NaN                  NaN